[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.4"
color-eyre = "0.6.3"
colored = "2.1.0"
crossterm = "0.27.0"
log = "0.4.21"
ratatui = "0.26.3"
rayon = "1.10.0"
regex = "1.10.4"
tui-logger = "0.11.1"
tui-term = "0.1.11"
